version: "3"
services:
  postgres:
    build: ./build/database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  task-api:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    restart: always