// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10001]
	_ = x[InvalidParam-10002]
	_ = x[InvalidPayload-10003]
	_ = x[Unauthorized-10004]
	_ = x[TooManyRequests-10005]
	_ = x[CreateTaskErr-20001]
	_ = x[GetTasksErr-20002]
	_ = x[UpdateTaskErr-20003]
	_ = x[DeleteTaskErr-20004]
	_ = x[GetTaskErr-20005]
	_ = x[TaskNotFound-20006]
	_ = x[GetTagsErr-20007]
	_ = x[DeleteTagErr-20008]
	_ = x[TagNotFound-20009]
	_ = x[RegisterErr-30001]
	_ = x[EmailTaken-30002]
	_ = x[LoginErr-30003]
	_ = x[InvalidCredentials-30004]
	_ = x[InvalidRefreshToken-30005]
	_ = x[RefreshErr-30006]
	_ = x[LogoutErr-30007]
}

const (
	_ErrCode_name_0 = "Server ErrorInvalid ParamInvalid PayloadUnauthorizedToo Many Requests"
	_ErrCode_name_1 = "Insert Task ErrorGet Tasks ErrorUpdate Task ErrorDelete Task ErrorGet Task ErrorTask Not FoundGet Tags ErrorDelete Tag ErrorTag Not Found"
	_ErrCode_name_2 = "Register ErrorEmail Already RegisteredLogin ErrorInvalid Email Or PasswordInvalid Refresh TokenRefresh ErrorLogout Error"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 12, 25, 40, 52, 69}
	_ErrCode_index_1 = [...]uint8{0, 17, 32, 49, 66, 80, 94, 108, 124, 137}
	_ErrCode_index_2 = [...]uint8{0, 14, 38, 49, 74, 95, 108, 120}
)

func (i ErrCode) String() string {
	switch {
	case 10001 <= i && i <= 10005:
		i -= 10001
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 20001 <= i && i <= 20009:
		i -= 20001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case 30001 <= i && i <= 30007:
		i -= 30001
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
