mode: local

Server:
  RunMode: debug
  HttpPort: 8080

App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

Database:
  DBType: postgres
  Username: postgres
  Password: password
  Host: postgres
  DBName: postgres