// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package error

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10001]
	_ = x[InvalidParam-10002]
	_ = x[InvalidPayload-10003]
	_ = x[CreateTaskErr-20001]
	_ = x[GetTasksErr-20002]
	_ = x[UpdateTaskErr-20003]
	_ = x[DeleteTaskErr-20004]
	_ = x[GetTaskErr-20005]
}

const (
	_ErrCode_name_0 = "ServerErrorInvalidParamInvalidPayload"
	_ErrCode_name_1 = "Insert Task ErrorGet Tasks ErrorUpdate Task ErrorDelete Task ErrorGet Task Error"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 11, 23, 37}
	_ErrCode_index_1 = [...]uint8{0, 17, 32, 49, 66, 80}
)

func (i ErrCode) String() string {
	switch {
	case 10001 <= i && i <= 10003:
		i -= 10001
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 20001 <= i && i <= 20005:
		i -= 20001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
