// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID        int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Status    int32          `gorm:"column:status;type:integer;not null" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
